###
# Test Login
POST http://127.0.0.1:9909/v1/auth/login
Content-Type: application/json

{
    "email": "testAccount@scrawlr.com",
    "password": "test1234"
}

###
# Incorrect post.destroy
DELETE http://127.0.0.1:9909/v1/posts/nPC9L7YjM558gdDHShS3cW2U_
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJUaGUgaXNzIChpc3N1ZXIpIGNsYWltIGlkZW50aWZpZXMgdGhlIHByaW5jaXBhbCB0aGF0IGlzc3VlZCB0aGUgSldUIiwiYXVkIjoiVGhlIHN1YiAoc3ViamVjdCkgY2xhaW0gaWRlbnRpZmllcyB0aGUgcHJpbmNpcGFsIHRoYXQgaXMgdGhlIHN1YmplY3Qgb2YgdGhlIEpXVCIsImlhdCI6MTYzODgyNTU2NCwiZXhwIjoxNjM4ODI1NjI0fQ.lObRyfCxwOYwruHi3KS2UTjPsDdrlcBubek01smXcDfQVQq2uDxNbnf177QNGa0eKflVXHDzfSifZksFEne9ag
